### ISSUE TITLE
Tab key only works in first line of XML code

### ISSUE THREAD

**Issue by NiekWe** [bellonemauro/Labonatip2.0#9]
:warning: This is a issue tracker :warning: 

In the editor, the XML tab the "Tab" key only works in the first line. If you press the Tab key in any other line it will but a tab in the first line.

## Your Environment

* Operating System and version:/
* Compiler:/
* Labonatip Version: 2.2.16

## Expected Behavior

In the editor/XML tabe when copy-pasting a command it end up on the left side. 
![image](https://user-images.githubusercontent.com/102161818/226343905-38a81f6d-dc97-43de-905b-76a77f4c1edc.png)
To move it aligned with other commands I automaticly press tab, which results in the first line losing it position.
![image](https://user-images.githubusercontent.com/102161818/226344062-82dbd431-4c89-4747-a093-afbe1e81d048.png)
When you have not noticed this error the complete protocol gets deleted.
![image](https://user-images.githubusercontent.com/102161818/226344190-4cef0373-cbdd-4a5a-bf6c-c5c7e23d9e0a.png)

## Possible Solution

Can the editor be made that the tab-key works properly?

**Comment by bellonemauro** [comment]
this happens because somebody mess up with the protocol, basically the user should not work on that window. That was only thought for very experienced users. If you mess up with that everything gets deleted (for safety), however, we can look at what was the specific issue and see if it is an unexpected behavior. 

BTW, do not use TAB to move lines, better to use "space key".

**Comment by NiekWe** [comment]
yes, that is also what I understood from other people, this should be a "4 space" indentation, not a tab.
I will close this issue.
